### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by thecodeduchess** [EileenRice/prj-rev-bwfs-tea-cozy#1]
https://github.com/EileenRice/prj-rev-bwfs-tea-cozy/blob/1ef05208b3cf6a2275a1390cea6d2a85940f1d06/TeaCozy/index.html#L122

Good! You included the copyright sign! Another write to write that would be **&copy** with semicolon at the end. If I include it in this note, it shows up as the sign haha.

**Comment by EileenRice** [comment]
Good to know and much easier than writing numbers!
